---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
library(lavaan)
library(banSEM)
```

# banSEM

banSEM (Bayesian network SEM) translates models fitted with lavaan to Bayesian networks
as implemented in the bnlearn package.

> **Warning**: banSEM is extremely experimental and not ready for use. It is just a 
playground to test the basic idea.

## Installation

You can install the development version of banSEM from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("jhorzek/netSEM")
```

## Example

```{r, message=FALSE}
library(lavaan)
library(banSEM)
model <- '
  # latent variable definitions
     ind60 =~ x1 + x2 + x3
     dem60 =~ y1 + a*y2 + b*y3 + c*y4
     dem65 =~ y5 + a*y6 + b*y7 + c*y8

  # regressions
    dem60 ~ ind60
    dem65 ~ ind60 + dem60

  # residual correlations
    y1 ~~ y5
    y2 ~~ y4 + y6
    y3 ~~ y7
    y4 ~~ y8
    y6 ~~ y8
'

lavaan_model <- sem(model,
                    data = PoliticalDemocracy,
                    meanstructure = TRUE)

network <- banSEM::banSEM(lavaan_model = lavaan_model)

# plot network
plot(network$dag)
```

```{r, message=FALSE, fig.height=3}
# Check conditional distribution
# probability that dem65 in (1,2) given dem60 > 1:
bnlearn::cpquery(fitted = network$bayes_net,
                 event = (dem65 > 1 & dem65 < 2),
                 evidence = (dem60 > 1))

# Get distribution under this assumption:
dist <- bnlearn::cpdist(fitted = network$bayes_net,
                       node = "dem65",
                       evidence = (dem60 > 1))
hist(dist$dem65)

# Now check dem60 < -1
dist <- bnlearn::cpdist(fitted = network$bayes_net,
                       node = "dem65",
                       evidence = (dem60 < -1))
hist(dist$dem65)


# simulate data from the network and refit SEM to check if the estimates align:
sim <- bnlearn::rbn(x = network$bayes_net, n = 10000)

fit_sim <- sem(model,
               data = sim[,lavaan_model@Data@ov.names[[1]]],
               meanstructure = TRUE)
round(abs(coef(fit_sim) -
            coef(lavaan_model)) / abs(coef(lavaan_model)), 3)
```

