---
title: "Factor-Scores"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Factor-Scores}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

**bnlearn** can also be used to compute the factor scores of the SEM. Those
factor scores appear to be identical to the regression scores in **OpenMx**:

```{r, message = FALSE}
library(bnSEM)
model <- '
  # latent variable definitions
     ind60 =~ x1 + x2 + x3
     dem60 =~ y1 + a*y2 + b*y3 + c*y4
     dem65 =~ y5 + a*y6 + b*y7 + c*y8

  # regressions
    dem60 ~ ind60
    dem65 ~ ind60 + dem60

  # residual correlations
    y1 ~~ y5
    y2 ~~ y4 + y6
    y3 ~~ y7
    y4 ~~ y8
    y6 ~~ y8
'

mx_model <- mxsem(model,
                  data = OpenMx::Bollen) |>
  mxTryHard()

fs <- mxFactorScores(mx_model, type = "Regression")

network <- bnSEM::bnSEM(mx_model = mx_model)
```

Let's predict the values of a single node, dem65:
```{r, message = FALSE}
# Predict dem65
fs[,3,1] - predict(network$bayes_net, 
                   "dem65", 
                   # Note: We need the extended data returned by bnSEM.
                   data = network$internal$extended_data,
                   # Note: We have to change the method, otherwise only
                   # parent nodes will be used for prediction.
                   method = "exact")
```

Alternatively, we can create predictions for all missing data (here: all
latent variables) with impute:
```{r, message = FALSE}
predicted_data <-  impute(network$bayes_net, 
                          data = network$internal$extended_data,
                          method = "exact")
# Predict dem60
fs[,2,1] - predicted_data$dem60

# Predict dem65
fs[,3,1] - predicted_data$dem65
```

